#!/usr/bin/env python3
# ----------------------------------------------------------------------------------------------
# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# ----------------------------------------------------------------------------------------------

"""Aggregate per-module .pyi fragments into per-submodule stub files.

Each codegen invocation emits a single .pyi covering one Einsums module.
Inside, entities are grouped under ``# %%submodule: <name>`` sentinels —
empty name means top-level (binds into ``einsums._core``).

This script merges every fragment in --frag-dir into the einsums package
layout under --pkg-dir:

    einsums/_core.pyi      ← top-level entities
    einsums/<submodule>.pyi ← per-submodule entities (e.g. linalg, graph)
    einsums/__init__.pyi   ← re-exports + py.typed marker
    einsums/py.typed       ← PEP 561 marker

Imports are deduplicated; the script writes a single shared header at
the top of each output file. Empty submodules are skipped.

If a submodule has a sibling hand-written helper module at
``--py-helpers-dir/<sub>.py`` (e.g. ``einsums/graph.py`` providing
``default_pass_manager`` on top of the compiled ``einsums._core.graph``),
its top-level public declarations are merged into ``<sub>.pyi``. Pyright
reads ``.pyi`` exclusively when both files exist, so without this merge
the helpers would be invisible to static analysis.
"""
from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

# Sentinel that groups entities by submodule inside a fragment.
SENTINEL = re.compile(r"^# %%submodule: (.*)$")

# The header block PyiEmitter writes; matched literally so we can strip
# it from each fragment and emit one shared header per output file.
HEADER_PREFIX = "from __future__ import annotations\n"

SHARED_HEADER = """\
# Auto-generated by apiary. Do not edit.
# pyright: reportInvalidTypeForm=false

from __future__ import annotations
from typing import Any, Literal, overload
from collections.abc import Callable
import enum
import numpy
import numpy.typing

"""

def _is_docstring(node: ast.stmt) -> bool:
    return (
        isinstance(node, ast.Expr)
        and isinstance(node.value, ast.Constant)
        and isinstance(node.value.value, str)
    )


def _stub_function(node: ast.FunctionDef | ast.AsyncFunctionDef) -> ast.FunctionDef | ast.AsyncFunctionDef:
    """Replace a def's body with ``[docstring,] ...`` while keeping the
    signature, decorators, and any annotations intact."""
    body: list[ast.stmt] = []
    if node.body and _is_docstring(node.body[0]):
        body.append(node.body[0])
    body.append(ast.Expr(value=ast.Constant(value=...)))
    node.body = body
    return node


def _stub_class(node: ast.ClassDef) -> ast.ClassDef:
    """Strip a class body down to docstring + public method/attribute stubs."""
    new_body: list[ast.stmt] = []
    for child in node.body:
        if _is_docstring(child):
            new_body.append(child)
        elif isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
            # Skip name-mangled single-underscore methods; keep dunder
            # methods (__init__, __getitem__, …) since they're part of
            # the public protocol pyright cares about.
            if child.name.startswith("_") and not child.name.startswith("__"):
                continue
            new_body.append(_stub_function(child))
        elif isinstance(child, (ast.Assign, ast.AnnAssign)):
            new_body.append(child)
    if not new_body:
        new_body.append(ast.Expr(value=ast.Constant(value=...)))
    node.body = new_body
    return node


def _public_assign_targets(node: ast.Assign | ast.AnnAssign) -> bool:
    """True if every target name in the assignment is public (no leading
    underscore), so it belongs in the rendered stub."""
    if isinstance(node, ast.AnnAssign):
        target = node.target
        return isinstance(target, ast.Name) and not target.id.startswith("_")
    for target in node.targets:
        if not isinstance(target, ast.Name) or target.id.startswith("_"):
            return False
    return True


def render_py_helpers(py_path: Path) -> str:
    """Render the public surface of a hand-written ``.py`` helper as a stub.

    Keeps every top-level import (decorators and type-hint helpers depend
    on them), public top-level ``def``/``class`` bodies (rewritten to
    ``...``), and public top-level constant assignments. Private top-level
    names (leading underscore) are dropped — they're implementation detail
    of the runtime shim, not part of the module's documented surface.
    """
    source = py_path.read_text()
    tree = ast.parse(source)
    keep: list[ast.stmt] = []
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            # SHARED_HEADER already pulls in ``from __future__ import
            # annotations``. Re-emitting it here produces a harmless but
            # ugly duplicate; skip it.
            if isinstance(node, ast.ImportFrom) and node.module == "__future__":
                continue
            keep.append(node)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_"):
                continue
            keep.append(_stub_function(node))
        elif isinstance(node, ast.ClassDef):
            if node.name.startswith("_"):
                continue
            keep.append(_stub_class(node))
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            if _public_assign_targets(node):
                keep.append(node)
    if not keep:
        return ""
    new_tree = ast.Module(body=keep, type_ignores=[])
    return ast.unparse(new_tree)


def parse_fragment(path: Path) -> dict[str, str]:
    """Return {submodule_name: body} for each ``# %%submodule:`` block."""
    text = path.read_text()
    blocks: dict[str, list[str]] = {}
    current: str | None = None
    for line in text.splitlines(keepends=True):
        m = SENTINEL.match(line.rstrip("\n"))
        if m is not None:
            current = m.group(1)
            blocks.setdefault(current, [])
            continue
        if current is None:
            # Lines before the first sentinel are the per-fragment
            # header (imports, banner). Discarded — we emit one shared
            # header per output.
            continue
        blocks[current].append(line)
    return {sm: "".join(lines).rstrip() + "\n" for sm, lines in blocks.items() if lines}


def load_overlay(overlay_path: Path) -> tuple[str, str]:
    """Parse a consumer-provided overlay stub into (module_funcs, class_methods).

    The overlay is a hand-written ``.pyi`` fragment describing runtime-patched
    members the C++ codegen can't see (Apiary itself is domain-agnostic). Its
    top-level ``def``\\s become module-level functions appended to
    ``__init__.pyi``; the methods of any class(es) it defines are collected into
    a 4-space-indented block injected into each ``_core.pyi`` class matching the
    caller's ``--overlay-class-regex``. Imports / other top-level statements are
    ignored — the shared header already supplies typing + numpy.
    """
    tree = ast.parse(overlay_path.read_text())
    funcs: list[ast.stmt] = []
    methods: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            funcs.append(_stub_function(node))
        elif isinstance(node, ast.ClassDef):
            for child in node.body:
                if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    rendered = ast.unparse(_stub_function(child))
                    methods.append("\n".join("    " + ln for ln in rendered.split("\n")))
    module_text = ast.unparse(ast.Module(body=funcs, type_ignores=[])) if funcs else ""
    return module_text, "\n".join(methods)


def inject_class_methods(core_text: str, methods_block: str, class_re: re.Pattern[str]) -> str:
    """Append the overlay method block to the end of each ``_core.pyi`` class
    whose ``class <Name>:`` line matches @p class_re — after the codegen
    members, so the class docstring stays first. A class body ends at the next
    column-0 statement (or EOF)."""
    if not methods_block:
        return core_text
    out: list[str] = []
    pending = False  # inside a target class, methods not yet appended

    def flush() -> None:
        nonlocal pending
        if pending:
            out.append(methods_block)
            pending = False

    for line in core_text.split("\n"):
        # A column-0 non-blank, non-comment line ends the current class body.
        if pending and line and not line[0].isspace() and not line.startswith("#"):
            flush()
        if class_re.match(line):
            flush()  # safety: close any still-open target class
            out.append(line)
            pending = True
            continue
        out.append(line)
    flush()  # EOF
    return "\n".join(out)


def aggregate(frag_dir: Path, pkg_dir: Path, py_helpers_dir: Path | None = None,
              overlay_path: Path | None = None, overlay_class_re: "re.Pattern[str] | None" = None) -> dict[str, Path]:
    """Read every *.pyi in `frag_dir` and write per-submodule files into `pkg_dir`.

    When ``py_helpers_dir`` is given, any ``<sub>.py`` file there whose name
    matches a generated submodule has its public surface appended to the
    submodule's ``.pyi`` so pyright (which prefers ``.pyi`` over a sibling
    ``.py``) still sees hand-written helpers.
    """
    by_sub: dict[str, list[str]] = {}
    for frag in sorted(frag_dir.glob("*.pyi")):
        for sub, body in parse_fragment(frag).items():
            by_sub.setdefault(sub, []).append(f"# from: {frag.name}\n{body}")

    # Optional consumer-provided overlay for members installed at runtime
    # (invisible to the C++ codegen): module-level functions for __init__.pyi,
    # and methods to inject into _core.pyi classes matching overlay_class_re.
    if overlay_path is not None:
        overlay_funcs, overlay_methods = load_overlay(overlay_path)
    else:
        overlay_funcs, overlay_methods = "", ""

    pkg_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for sub, parts in by_sub.items():
        out_name = "_core.pyi" if sub == "" else f"{sub}.pyi"
        out_path = pkg_dir / out_name
        text = SHARED_HEADER + "\n".join(parts).rstrip() + "\n"
        # Hand-written helper modules only exist for named submodules
        # (graph.py, …) — there is no top-level einsums-package helper
        # that needs to merge into _core.pyi.
        if py_helpers_dir is not None and sub:
            helper_py = py_helpers_dir / f"{sub}.py"
            if helper_py.is_file():
                helper_stub = render_py_helpers(helper_py)
                if helper_stub:
                    text += f"\n# helpers from einsums/{sub}.py\n{helper_stub.rstrip()}\n"
        # Attach the overlay's runtime-patched methods to matching _core classes.
        if sub == "" and overlay_class_re is not None:
            text = inject_class_methods(text, overlay_methods, overlay_class_re)
        out_path.write_text(text)
        written[sub] = out_path

    # PEP 561: empty marker file telling type-checkers this package
    # ships its own stubs.
    (pkg_dir / "py.typed").write_text("")

    # __init__.pyi: re-export everything from _core so ``import einsums``
    # gives pyright the full top-level surface, plus an explicit
    # re-export of each generated submodule. At runtime the package's
    # __getattr__ lazy-binds these to einsums._core.<sub>, so pyright
    # needs the static hint to know they exist as attributes of einsums.
    # The `as X` form is PEP 484's explicit re-export marker.
    submodule_names = sorted(sub for sub in written if sub)
    # Pure-Python helper sub-packages (e.g. ``einsums/testing/``) have no
    # C++ fragment, so they never appear in ``written``. Surface them so
    # pyright resolves ``from einsums.testing import …`` — and emit each
    # one's ``__init__.pyi`` from the source. Without an explicit stub
    # pyright treats the parent's ``__init__.pyi`` as authoritative for
    # submodule resolution and the .py source becomes invisible.
    pkg_helper_names: list[str] = []
    if py_helpers_dir is not None:
        for child in sorted(py_helpers_dir.iterdir()):
            if (child.is_dir()
                    and (child / "__init__.py").is_file()
                    and child.name not in submodule_names):
                pkg_helper_names.append(child.name)
                # Mirror the source layout into the destination so pyright
                # finds a stub for each sub-package alongside the .py.
                helper_stub = render_py_helpers(child / "__init__.py")
                if helper_stub:
                    sub_dir = pkg_dir / child.name
                    sub_dir.mkdir(parents=True, exist_ok=True)
                    (sub_dir / "__init__.pyi").write_text(
                        SHARED_HEADER + helper_stub.rstrip() + "\n"
                    )
    all_sub_names = sorted(set(submodule_names) | set(pkg_helper_names))
    init_pyi = pkg_dir / "__init__.pyi"
    init_body = SHARED_HEADER + "from einsums._core import *  # noqa: F401,F403\n"
    if all_sub_names:
        init_body += "\n"
        for sub in all_sub_names:
            init_body += f"from . import {sub} as {sub}\n"
    # Overlay module-level functions (runtime-patched; not in _core).
    if overlay_funcs:
        init_body += "\n# Overlay module-level functions (runtime-patched)\n" + overlay_funcs.rstrip() + "\n"
    init_pyi.write_text(init_body)

    return written


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--frag-dir", required=True, type=Path,
                   help="Directory containing per-module .pyi fragments.")
    p.add_argument("--pkg-dir", required=True, type=Path,
                   help="Destination einsums/ package directory.")
    p.add_argument("--py-helpers-dir", type=Path, default=None,
                   help="Source directory of hand-written <sub>.py helper "
                        "modules. When set, public top-level decls in "
                        "<sub>.py are merged into <sub>.pyi.")
    p.add_argument("--overlay", type=Path, default=None,
                   help="Optional .pyi overlay describing members installed at "
                        "runtime (invisible to the codegen): top-level defs go to "
                        "__init__.pyi; class methods inject into _core.pyi classes "
                        "matching --overlay-class-regex.")
    p.add_argument("--overlay-class-regex", default=None,
                   help="Regex matched against ``class <Name>:`` lines in "
                        "_core.pyi; matching classes receive the overlay methods.")
    args = p.parse_args(argv)

    if not args.frag_dir.is_dir():
        print(f"aggregate_stubs: {args.frag_dir} is not a directory", file=sys.stderr)
        return 1
    if args.py_helpers_dir is not None and not args.py_helpers_dir.is_dir():
        print(f"aggregate_stubs: {args.py_helpers_dir} is not a directory", file=sys.stderr)
        return 1
    if args.overlay is not None and not args.overlay.is_file():
        print(f"aggregate_stubs: overlay {args.overlay} is not a file", file=sys.stderr)
        return 1
    overlay_re = re.compile(args.overlay_class_regex) if args.overlay_class_regex else None

    written = aggregate(args.frag_dir, args.pkg_dir, args.py_helpers_dir, args.overlay, overlay_re)
    if written:
        names = ", ".join(sorted(p.name for p in written.values()))
        print(f"aggregate_stubs: wrote {names} to {args.pkg_dir}")
    else:
        print("aggregate_stubs: no .pyi fragments found", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
